/* ============================================================================
   Mills Maths Tools — Resources by Stage : TOOL LINKS  (auto-derived)
   ----------------------------------------------------------------------------
   Interactive tools, student quizzes, worksheet makers, flip cards, games and
   ELPSA lesson plans, mapped to the NSW syllabus outcome each one serves.

   WHY THIS IS A SEPARATE FILE
   ---------------------------
   `resourcesManifest.js` holds the outcomes and YOUR uploaded PDFs — that is
   the file you hand-edit. This file is the wiring for pages that already exist
   elsewhere on the site, so it can be regenerated by walking the repo without
   touching anything you have typed.

   SHAPE
   -----
     "MA4-ALG-C-01": [ { title, kind, url, note, tags[] }, ... ]

   `kind` renders as the small right-hand label and drives sort order within an
   outcome: Teacher tool -> Lesson plan -> Student quiz -> Worksheet maker ->
   Flip cards -> Game.

   NOTES
   -----
   * A tool may appear under several outcomes on purpose (cross-listing). The
     Protractor tool serves both MA3-GM-03 and MA4-ANG-C-01; nothing is
     duplicated on disk, both rows point at the same URL.
   * All URLs are site-absolute so they work from any page depth.
   * The Revision Generator (Exam Builder) is deliberately NOT listed here.
   ========================================================================== */

window.MMT_TOOL_LINKS = {
  "MA3-2DS-01": [
    {
      title: "Math Memory — Shapes",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching shapes with their names or properties.",
      tags: ["game", "memory", "2D shapes", "classifying", "matching"]
    }
  ],

  "MA3-2DS-02": [
    {
      title: "Area Model Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/",
      note: "Split and rearrange a rectangle to build area and perimeter reasoning.",
      tags: ["area", "perimeter", "rectangles", "area model", "partitioning"]
    },
    {
      title: "Rectangles — Area / Perimeter",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/perimeter-area-rectangle.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "area", "perimeter", "rectangles"]
    },
    {
      title: "Shikaku",
      kind: "Game",
      url: "/games/shikaku.html",
      note: "Divide the grid into rectangles whose areas match the clue numbers.",
      tags: ["game", "puzzle", "area", "rectangles", "factors", "logic"]
    }
  ],

  "MA3-2DS-03": [
    {
      title: "Area of a Triangle — Half the Rectangle",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/area-of-a-triangle/",
      note: "Shows a triangle as half its enclosing rectangle, draggable.",
      tags: ["area", "triangles", "rectangles", "derivation", "visual"]
    }
  ],

  "MA3-3DS-02": [
    {
      title: "Unit Conversion \u2014 Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/unit-conversion-number-line/",
      note: "Capacity conversions on a double number line \u2014 kL, L and mL \u2014 built from the 1 : 1000 anchor.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "capacity", "volume", "kL", "L", "mL"]
    },
    {
      title: "Converting Units of Measurement",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/unit-conversion.html",
      note: "Capacity conversions on and off the number line, four levels, Stage 3 setting for kL, L and mL. Trilingual, with an answer key.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "capacity", "volume", "kL", "L", "mL", "worksheet generator", "printable", "trilingual"]
    },
  ],

  "MA3-AR-01": [
    {
      title: "Partition Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/partition-splitter/",
      note: "Split a number into parts on a place-value display to model addition strategies.",
      tags: ["partitioning", "place value", "addition", "mental strategies"]
    },
    {
      title: "Rows & Columns Challenge",
      kind: "Game",
      url: "/games/row-column-challenge.html",
      note: "Two-player strategy game: take a number from the active row or column and add it to your total. After Dr Paul Swan.",
      tags: ["game", "strategy", "addition", "mental computation", "two player"]
    },
    {
      title: "Partition Splitter — Class Flash Cards",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/partition-splitter/partition-flash.html",
      note: "Projected partitioning flash round for the whole class.",
      tags: ["flash cards", "partitioning", "whole class"]
    },
    {
      title: "Partition Splitter — Student Practice",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/partition-splitter/student-flash.html",
      note: "Self-paced student partitioning practice.",
      tags: ["flash cards", "partitioning", "independent practice"]
    }
  ],

  "MA3-CHAN-01": [
    {
      title: "Probability Spinner Simulator",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Build a spinner, run trials, compare observed with expected frequency.",
      tags: ["probability", "spinner", "simulation", "expected value", "experiment"]
    },
    {
      title: "Greedy Pig",
      kind: "Game",
      url: "/games/greedy-pig.html",
      note: "Teacher-led risk and reward dice game — bank before the poison number. Class leaderboard.",
      tags: ["game", "probability", "risk", "expected value", "whole class", "teacher led"]
    },
    {
      title: "Taxed by the King",
      kind: "Game",
      url: "/games/taxed-by-the-king.html",
      note: "Teacher-led card probability game — bank before the King takes his tax. Class leaderboard.",
      tags: ["game", "probability", "risk", "cards", "whole class", "teacher led"]
    }
  ],

  "MA3-GM-01": [
    {
      title: "Capture the Grid",
      kind: "Game",
      url: "/games/cartesian-capture.html",
      note: "Claim coordinate points to capture territory on the Cartesian plane.",
      tags: ["game", "coordinates", "Cartesian plane", "strategy", "two player"]
    },
    {
      title: "Coordinate Battleships",
      kind: "Game",
      url: "/games/battleships.html",
      note: "Place ships on a coordinate grid and attack by typing ordered pairs.",
      tags: ["game", "coordinates", "ordered pairs", "Cartesian plane", "two player"]
    },
    {
      title: "Coordinate Connect 4",
      kind: "Game",
      url: "/games/cartesian-connect-4.html",
      note: "Connect four by naming coordinate pairs.",
      tags: ["game", "coordinates", "Cartesian plane", "two player"]
    }
  ],

  "MA3-GM-02": [
    {
      title: "Unit Conversion \u2014 Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/unit-conversion-number-line/",
      note: "Metric length conversions on a double number line: the 1 : ratio anchor stays on screen and every value is the same scaling of it. km, m, cm and mm.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "length", "km", "m", "cm", "mm"]
    },
    {
      title: "Converting Units of Measurement",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/unit-conversion.html",
      note: "Fill a whole number line, then one jump, then bare conversions, comparing and word problems. Stage 3 setting uses neighbouring units only. Trilingual, with an answer key.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "length", "km", "m", "cm", "mm", "worksheet generator", "printable", "trilingual"]
    },
  ],

  "MA3-GM-03": [
    {
      title: "Protractor Angle Explorer",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/reading-a-protractor/",
      note: "Drag a protractor onto an angle and read the scale, inner and outer.",
      tags: ["protractor", "measuring angles", "angle types"]
    },
    {
      title: "Reading a Protractor",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/reading-a-protractor.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "protractor", "measuring angles"]
    },
    {
      title: "Angle Types Flip Fluency",
      kind: "Flip cards",
      url: "/flip-cards/Geometry/angles.html",
      note: "Flip-card fluency on acute, obtuse, reflex and right angles.",
      tags: ["flip cards", "angle types", "fluency", "classifying"]
    }
  ],

  "MA3-MR-01": [
    {
      title: "Halve and Halve Again",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/halve-and-halve-again/",
      note: "A bar model cut in half, and in half again. The amount swells and pops into two equal halves that fall into place; halving twice is \u00f7 4 and three times is \u00f7 8, and the last press lifts one part out to become the answer. A halving ladder records each step and the check doubles back up it.",
      tags: ["division", "halving", "halve", "doubling", "bar model", "tape diagram", "part whole", "equal parts", "halves quarters eighths", "mental strategies", "partitioning", "fraction of an amount", "inverse", "multiplication", "visual", "whole-class teaching"]
    },
    {
      title: "Division by Grouping \u2014 Bubbles",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/division-grouping-bubbles/",
      note: "Share a number into 2\u20136 equal bubbles a chunk at a time. The chunk flies to the first group then copies to every other one, a running tally counts up as each lands, and the chunks add to the quotient.",
      tags: ["division", "sharing", "equal groups", "partial quotients", "chunking", "repeated subtraction", "remainder", "partitioning", "visual", "whole-class teaching", "inverse", "multiplication"]
    },
    {
      title: "Division by Grouping \u2014 Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/division-grouping.html",
      note: "Printable A4 with the bubbles drawn on the page: finish a started round, share it out, the partial-quotient table alone, remainders, and word problems. Trilingual, with an answer key that shows the rounds.",
      tags: ["worksheet generator", "printable", "division", "sharing", "equal groups", "partial quotients", "chunking", "remainder", "short division", "answer key", "trilingual", "eald"]
    },
    {
      title: "Division by Grouping \u2014 Student Quiz",
      kind: "Student quiz",
      url: "/online-quizzes/stage-3/number/division-grouping.html",
      note: "Sweet to Spicy, where the level is how much of the teaching tool the student keeps \u2014 Sweet hands over the whole thing, Spicy takes the bubbles away. Saves to the student dashboard.",
      tags: ["quiz", "division", "sharing", "equal groups", "partial quotients", "chunking", "remainder", "inverse", "word problems", "sweet mild medium spicy", "student code login", "teacher dashboard", "achievements"]
    },
    {
      title: "Factor Circles — Teacher Explore",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/factor-circles/",
      note: "Arrange dots in a circle to reveal factor pairs and groupings.",
      tags: ["factors", "multiples", "factor pairs", "arrays", "visual"]
    },
    {
      title: "Times Table Chart — Area, Product, Division, Fractions",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/timestable-chart/",
      note: "One chart, four lenses: array area, product, division and fraction of an amount.",
      tags: ["times tables", "arrays", "multiplication", "division", "factors", "visual"]
    },
    {
      title: "Products & Factors — Escape the Factor Circle Room",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/factor-circles.html",
      note: "Escape-room styled quiz on products and factors. Saves to the student dashboard.",
      tags: ["quiz", "factors", "products", "escape room", "gamified"]
    },
    {
      title: "Factoring for Multiplication",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/multiplicative-strategies/",
      note: "Generates worksheets on factorising to make multiplication easier.",
      tags: ["worksheet generator", "printable", "factors", "multiplicative strategies"]
    },
    {
      title: "Factors Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/factor-circles.html",
      note: "Generates printable factor worksheets.",
      tags: ["worksheet generator", "printable", "factors"]
    },
    {
      title: "Closest to 100",
      kind: "Game",
      url: "/games/closest-to-100.html",
      note: "Roll two dice, state the product, then draw the matching array on a hundred grid. Closest to 100 wins.",
      tags: ["game", "dice", "arrays", "multiplication", "area", "two player"]
    },
    {
      title: "Dots and Boxes (Multiples mode)",
      kind: "Game",
      url: "/games/dots-and-boxes.html",
      note: "Roll a product, then claim an edge touching a matching multiple. Classic mode also available.",
      tags: ["game", "multiples", "products", "times tables", "strategy", "two player"]
    },
    {
      title: "Math Memory — Multiplication",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching multiplication facts.",
      tags: ["game", "memory", "multiplication", "fluency", "matching"]
    }
      ,
    {
      title: "Division with a Ratio Table",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/ratio-table-division/",
      note: "A ratio table built from known products. Every row is entered as a pair \u2014 the groups, then the total \u2014 and when a row lands on the number being divided, its left column is the answer.",
      tags: ["division", "ratio table", "known products", "proportional reasoning", "multiplicative thinking", "partial quotients", "doubling", "halving", "missing factor", "inverse", "multiplication", "two-digit divisor", "visual", "whole-class teaching"]
    }
      ,
    {
      title: "Division with a Ratio Table \u2014 Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/ratio-table-division.html",
      note: "Printable A4 ratio tables: finish one already begun, build one from a single given row, plot the rows on a grid, and word problems that ask how many groups fit. Trilingual, with an answer key that shows a route through the table.",
      tags: ["worksheet generator", "printable", "division", "ratio table", "known products", "proportional reasoning", "multiplicative thinking", "doubling", "halving", "missing factor", "two-digit divisor", "answer key", "trilingual"]
    }
  ],

  "MA3-MR-02": [
    {
      title: "Division by Grouping \u2014 Bubbles",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/division-grouping-bubbles/",
      note: "Finishes every question with both number sentences \u2014 84 \u00f7 6 = 14 and 6 \u00d7 14 = 84 \u2014 so division and multiplication are read as the same fact.",
      tags: ["number sentences", "division", "multiplication", "inverse", "equal groups", "partial quotients", "remainder", "visual", "whole-class teaching"]
    }
    ,
    {
      title: "Division by Grouping \u2014 Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/division-grouping.html",
      note: "Every question ends with the inverse check \u2014 6 \u00d7 ___ = 84 \u2014 so a division sentence and its multiplication are written side by side.",
      tags: ["worksheet generator", "printable", "number sentences", "division", "multiplication", "inverse", "equal groups", "partial quotients", "answer key"]
    }
    ,
    {
      title: "Division by Grouping \u2014 Student Quiz",
      kind: "Student quiz",
      url: "/online-quizzes/stage-3/number/division-grouping.html",
      note: "A whole section of questions is the missing factor \u2014 6 \u00d7 ? = 84 \u2014 so a division sentence and its multiplication are answered as the same fact.",
      tags: ["quiz", "number sentences", "division", "multiplication", "inverse", "missing factor", "equal groups", "remainder", "student code login", "teacher dashboard"]
    }
      ,
    {
      title: "Division with a Ratio Table",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/ratio-table-division/",
      note: "Finishes every question with both number sentences \u2014 18 \u00d7 15 = 270 and 270 \u00f7 15 = 18 \u2014 because the table is asking how many groups, which is the missing factor.",
      tags: ["number sentences", "division", "multiplication", "inverse", "missing factor", "ratio table", "known products", "patterns", "visual", "whole-class teaching"]
    }
      ,
    {
      title: "Division with a Ratio Table \u2014 Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/ratio-table-division.html",
      note: "Every question can end with the check sentence \u005f\u005f\u005f \u00d7 15 = 270, so the division on the page and its multiplication are written side by side.",
      tags: ["worksheet generator", "printable", "number sentences", "division", "multiplication", "inverse", "missing factor", "ratio table", "answer key", "trilingual"]
    }
    ,
    {
      title: "Halve and Halve Again",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/halve-and-halve-again/",
      note: "Finishes every question with the inverse written out \u2014 4 \u00d7 24 = 96 \u2014 and checks it by doubling back up the same ladder the halving came down.",
      tags: ["number sentences", "division", "multiplication", "inverse", "halving", "doubling", "equal parts", "bar model", "visual", "whole-class teaching"]
    }

  ],

  "MA3-NSM-01": [
    {
      title: "Unit Conversion \u2014 Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/unit-conversion-number-line/",
      note: "Metric mass conversions on a double number line \u2014 kg and g \u2014 built from the 1 : 1000 anchor rather than a rule about zeros.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "mass", "kg", "g", "tonnes"]
    },
    {
      title: "Converting Units of Measurement",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/unit-conversion.html",
      note: "Mass conversions on and off the number line, four levels, Stage 3 setting for kg and g. Trilingual, with an answer key.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "mass", "kg", "g", "tonnes", "worksheet generator", "printable", "trilingual"]
    },
  ],

  "MA3-NSM-02": [
    {
      title: "Math Memory — Clocks",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching analogue clocks to digital times.",
      tags: ["game", "memory", "time", "analogue", "digital", "matching"]
    }
  ],

  "MA3-RN-01": [
    {
      title: "Place Value: Multiply & Divide by 10",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/multiply-divide-by-ten/",
      note: "Drag digits through a place-value grid to see ×10 and ÷10 shift the whole number.",
      tags: ["place value", "powers of 10", "decimals", "multiply", "divide"]
    },
    {
      title: "Whole Number Zoom Rounding",
      kind: "Student quiz",
      url: "/online-quizzes/stage-3/number/whole-number-zoom.html",
      note: "Zoomable number line for rounding whole numbers. Saves to the student dashboard.",
      tags: ["rounding", "number line", "place value", "quiz"]
    },
    {
      title: "Multiply & Divide by Powers of 10",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/multiply-divide-by-ten.html",
      note: "Generates a printable worksheet with answers.",
      tags: ["worksheet generator", "printable", "powers of 10"]
    },
    {
      title: "Divide by 10",
      kind: "Flip cards",
      url: "/flip-cards/divide-by-tens.html",
      note: "Quick flip-card fluency on dividing by 10.",
      tags: ["flip cards", "fluency", "division", "place value"]
    },
    {
      title: "Multiply & Divide by 10 — Class Flash Cards",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/multiply-divide-by-ten/flash-cards.html",
      note: "Whole-class projected flash card round.",
      tags: ["flash cards", "fluency", "place value", "whole class"]
    },
    {
      title: "Multiply & Divide by 10 — Student Practice",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/multiply-divide-by-ten/student-flash.html",
      note: "Self-paced student version of the flash cards.",
      tags: ["flash cards", "fluency", "independent practice"]
    }
  ],

  "MA3-RN-03": [
    {
      title: "Math Memory — Fractions & Decimals",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching each fraction to its decimal form. Pass-and-play or online.",
      tags: ["game", "memory", "equivalence", "fractions", "decimals", "matching"]
    }
  ],

  "MA3-RQF-01": [
    {
      title: "Fraction Hex Path",
      kind: "Game",
      url: "/games/fractional-hex.html",
      note: "Simplify a fraction to claim a hex; build an unbroken path across the board.",
      tags: ["game", "simplifying fractions", "equivalence", "strategy", "two player"]
    }
  ],

  "MA3-RQF-02": [
    {
      title: "Times Table Chart — Fractions of an Amount",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-of-amount/",
      note: "Uses the times-table grid to find a fraction of an amount.",
      tags: ["fraction of an amount", "times tables", "visual", "arrays"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-of-amount.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "fraction of an amount"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-of-amount.html",
      note: "Generates printable questions with answers.",
      tags: ["worksheet generator", "printable", "fraction of an amount"]
    }
  ],

  "MA4-ALG-C-01": [
    {
      title: "Collecting Like Terms",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/collecting-like-terms/",
      note: "Group and combine like terms with visual term tiles.",
      tags: ["algebra", "like terms", "simplifying", "coefficients", "visual"]
    },
    {
      title: "Number Pattern (Coefficient Groups)",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/number-groups/",
      note: "Set how many terms and the total of the coefficients, then reveal and combine.",
      tags: ["algebra", "like terms", "coefficients", "generalising", "patterns"]
    },
    {
      title: "Substitution in Algebra",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/substitution/",
      note: "Substitute values into expressions and watch each step evaluate.",
      tags: ["algebra", "substitution", "evaluating", "expressions"]
    },
    {
      title: "Collecting Like Terms — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/collecting-like-terms/lesson-plan.html",
      note: "Full ELPSA sequence for the like-terms tool.",
      tags: ["lesson plan", "ELPSA", "algebra", "planning"]
    },
    {
      title: "Number Pattern — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/number-groups/lesson-plan.html",
      note: "Full ELPSA sequence for the coefficient-groups tool.",
      tags: ["lesson plan", "ELPSA", "algebra", "planning"]
    },
    {
      title: "Substitution in Algebra — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/substitution/lesson-plan.html",
      note: "Full ELPSA sequence for the substitution tool.",
      tags: ["lesson plan", "ELPSA", "algebra", "planning"]
    },
    {
      title: "Algebraic Techniques",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/algebraic-techniques.html",
      note: "Covers simplifying, expanding and factorising. Sub-topic quiz links can be built from this page.",
      tags: ["quiz", "algebra", "simplifying", "expanding", "factorising", "subset builder"]
    },
    {
      title: "Collecting Like Terms",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/collecting-like-terms.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "algebra", "like terms", "simplifying"]
    },
    {
      title: "Number Groups",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/number-groups.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "algebra", "like terms", "coefficients"]
    },
    {
      title: "Substitution in Algebra",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/substitution.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "algebra", "substitution", "evaluating"]
    },
    {
      title: "Algebraic Techniques",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/algebraic-techniques/",
      note: "Generates printable algebra worksheets with answers.",
      tags: ["worksheet generator", "printable", "algebra", "simplifying", "expanding"]
    },
    {
      title: "Collecting Like Terms",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/collecting-like-terms.html",
      note: "Generates printable like-terms worksheets.",
      tags: ["worksheet generator", "printable", "like terms"]
    },
    {
      title: "Collecting Like Terms (Number Groups)",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/number-groups.html",
      note: "Coefficient-group variant of the like-terms worksheet creator.",
      tags: ["worksheet generator", "printable", "like terms", "coefficients"]
    },
    {
      title: "Substitution in Algebra",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/substitution.html",
      note: "Generates printable substitution worksheets.",
      tags: ["worksheet generator", "printable", "substitution"]
    },
    {
      title: "Translate Words to Algebra",
      kind: "Flip cards",
      url: "/flip-cards/algebra-to-words.html",
      note: "Flip-card fluency converting worded phrases into algebraic expressions.",
      tags: ["flip cards", "fluency", "algebra", "worded problems", "translating"]
    }
  ],

  "MA4-ANG-C-01": [
    {
      title: "Angle Relationships on Parallel Lines",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/angles-parallel-lines/",
      note: "Drag a transversal across parallel lines and watch co-interior, alternate and corresponding angles update.",
      tags: ["angles", "parallel lines", "transversal", "corresponding", "alternate", "co-interior"]
    },
    {
      title: "Protractor Angle Explorer",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/reading-a-protractor/",
      note: "Drag a protractor onto an angle and read the scale, inner and outer.",
      tags: ["protractor", "measuring angles", "angle types"]
    },
    {
      title: "Angle Relationships",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/angle-relationships.html",
      note: "Sub-topic quiz links can be built from this page.",
      tags: ["quiz", "angles", "parallel lines", "transversal", "subset builder"]
    },
    {
      title: "Reading a Protractor",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/reading-a-protractor.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "protractor", "measuring angles"]
    },
    {
      title: "Angle Relationships",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/angle-relationships/",
      note: "Generates printable angle-relationship worksheets with diagrams.",
      tags: ["worksheet generator", "printable", "angles", "parallel lines"]
    },
    {
      title: "Angle Relationships",
      kind: "Flip cards",
      url: "/flip-cards/Angles-parallel-lines/",
      note: "Flip-card fluency on angle relationships formed by parallel lines.",
      tags: ["flip cards", "fluency", "angles", "parallel lines", "transversal"]
    },
    {
      title: "Angle Types Flip Fluency",
      kind: "Flip cards",
      url: "/flip-cards/Geometry/angles.html",
      note: "Flip-card fluency on acute, obtuse, reflex and right angles.",
      tags: ["flip cards", "fluency", "angle types", "classifying"]
    }
  ],

  "MA4-ARE-C-01": [
    {
      title: "Area Model Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/",
      note: "Split and rearrange a rectangle to build area reasoning and composite area.",
      tags: ["area", "rectangles", "area model", "composite area", "partitioning"]
    },
    {
      title: "Area of a Triangle — Half the Rectangle",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/area-of-a-triangle/",
      note: "Shows a triangle as half its enclosing rectangle, draggable.",
      tags: ["area", "triangles", "rectangles", "derivation", "visual"]
    },
    {
      title: "Area Model",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/area-model.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "area", "area model", "composite area"]
    },
    {
      title: "Area of a Triangle",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/area-of-a-triangle.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "area", "triangles"]
    },
    {
      title: "Triangles — Area Worksheet Maker",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/area-of-a-triangle.html",
      note: "Generates printable triangle-area worksheets.",
      tags: ["worksheet generator", "printable", "area", "triangles"]
    },
    {
      title: "Shikaku",
      kind: "Game",
      url: "/games/shikaku.html",
      note: "Divide the grid into rectangles whose areas match the clue numbers.",
      tags: ["game", "puzzle", "area", "rectangles", "factors", "logic"]
    }
  ],

  "MA4-EQU-C-01": [
    {
      title: "Equations — Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/double-numberline/",
      note: "Solve one- and two-step equations on a double number line, keeping both sides balanced.",
      tags: ["equations", "double number line", "solving", "inverse operations", "balance"]
    },
    {
      title: "Double Number Line Equations — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/double-numberline/lesson-plan.html",
      note: "Full ELPSA sequence for the double number line tool.",
      tags: ["lesson plan", "ELPSA", "equations", "planning"]
    },
    {
      title: "Addition & Subtraction Equations",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/double-numberline/student-quiz-add-subtract.html",
      note: "One-step equations, additive. Saves to the student dashboard.",
      tags: ["quiz", "equations", "one step", "addition", "subtraction"]
    },
    {
      title: "Equations",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/equations.html",
      note: "Sub-topic quiz links can be built from this page.",
      tags: ["quiz", "equations", "solving", "subset builder"]
    },
    {
      title: "Equations — Double Number Line",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/double-numberline/student-quiz.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "equations", "double number line"]
    },
    {
      title: "Multiplication & Division Equations",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/double-numberline/student-quiz-mult-div.html",
      note: "One-step equations, multiplicative. Saves to the student dashboard.",
      tags: ["quiz", "equations", "one step", "multiplication", "division"]
    },
    {
      title: "Equations",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/equations/",
      note: "Generates printable equation worksheets with answers.",
      tags: ["worksheet generator", "printable", "equations"]
    },
    {
      title: "One Step Equations",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/double-numberline.html",
      note: "Generates printable one-step equation worksheets.",
      tags: ["worksheet generator", "printable", "equations", "one step"]
    }
  ],

  "MA4-FRC-C-01": [
    {
      title: "Decimal Zoom Rounding",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/rounding-decimals/",
      note: "Zoom into a number line to see which decimal place a value rounds to.",
      tags: ["rounding", "decimals", "number line", "zoom", "place value"]
    },
    {
      title: "Fraction Grid to Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-grid-number-line/",
      note: "The hundred flat (or any area grid) is shaded, then its parts lift off and rearrange into the whole journey from 0 to 1 \u2014 so a part-whole count becomes ONE point on a number line. Estimate-first, benchmark ghosts, regroup-and-rename, decimal, percentage and a second fraction to compare.",
      tags: ["fractions", "decimals", "percentages", "number line", "area model", "hundred grid", "MAB", "part-whole", "equivalent fractions", "estimation", "density", "comparing fractions", "recurring"]
    },
    {
      title: "Fraction Grid to Number Line",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-grid-number-line.html",
      note: "Every card carries the area grid AND a number line, so the fraction has to travel between them. Four question kinds \u2014 shade then place the point, place then shade, name it four ways, and compare two \u2014 plus a full-width misconception prompt on each page. The ladder raises the demand on the LINE: matching parts, then tenths, then a different unit, then only 0, \u00bd and 1.",
      tags: ["worksheet", "fractions", "decimals", "percentages", "number line", "area model", "hundred grid", "equivalent fractions", "simplest form", "comparing fractions", "reasoning", "misconceptions"]
    },
    {
      title: "Fraction Bar + Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-bar-number-line/",
      note: "One fraction shown three ways: part-whole bar, point on a double number line, and as division. Denominators 2-100.",
      tags: ["fractions", "decimals", "number line", "fraction bar", "division", "equivalence", "recurring"]
    },
    {
      title: "Fraction to Percentage",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-to-percentage/",
      note: "Fraction above the line, percentage below. Step-by-step reveals find one part of 100, then count on. Estimate-first predict mode; handles recurring percentages and past 100%.",
      tags: ["fractions", "percentages", "conversion", "number line", "estimation", "recurring", "per cent", "unit fraction"]
    },
    {
      title: "Adding and Subtracting Fractions",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/adding-fractions/",
      note: "Two fraction bars join on a number line, are renamed with a common denominator (equivalents shown under the bar), and the pieces are counted. Predict mode, a misconception step, and subtraction that can pass zero.",
      tags: ["fractions", "adding fractions", "subtracting fractions", "common denominator", "equivalent fractions", "number line", "bar model", "renaming", "negatives"]
    },
    {
      title: "Multiplying Fractions \u2014 Area Model",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/multiplying-fractions-area-model/",
      note: "One unit square, cut into columns by one fraction and rows by the other. Five reveals: the blank whole, shade the second fraction, take the first fraction of it (the overlap goes darker), name every piece the whole is now cut into, then the answer appears in the middle of the overlap. A Simplify button then slides the pieces into their simplest grouping (and Undo puts them back). An opt-in number line replays the same steps in one dimension, a \"read it the other way\" swap shows commutativity, and decimal / percentage labels plus a tenths tier show why 0.4 \u00d7 0.6 has two decimal places. Deliberately almost no on-screen text \u2014 the talking is the teacher's.",
      tags: ["fractions", "multiplying fractions", "area model", "unit square", "of", "product", "denominators multiply", "numerators multiply", "simplifying", "commutativity", "decimals", "percentages", "hundredths", "estimation", "misconceptions"]
    },
    {
      title: "Multiplying Fractions \u2014 Area Model",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/multiplying-fractions.html",
      note: "Five lettered sections, each handing the student a different amount of the model: shade a square already cut both ways; finish one where only the second fraction is cut and shaded; read a shaded model backwards and write the multiplication; cut up a blank square yourself; or plain fluency with no model at all. Three models per row, four spice levels, a simplest-form step, an answer key with the models shaded in, and a misconception to argue with at the foot of every page. Trilingual EN / AR / FA \u2014 instructions print bilingually, the maths stays Western.",
      tags: ["worksheet", "fractions", "multiplying fractions", "area model", "unit square", "shading", "of", "denominators multiply", "numerators multiply", "simplifying", "reasoning", "misconceptions", "answer key"]
    },
    {
      title: "Times Table Chart — Fractions of an Amount",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-of-amount/",
      note: "Uses the times-table grid to find a fraction of an amount.",
      tags: ["fraction of an amount", "times tables", "visual", "arrays"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-of-amount.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "fraction of an amount"]
    },
    {
      title: "Adding and Subtracting Fractions",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/adding-subtracting-fractions.html",
      note: "Five levels, 15 questions, trilingual EN/AR/FA, with an equation-editor answer box (fraction button). Sweet counts like parts; Mild renames one bar; Medium renames both (all three have back/forward reveal arrows); Spicy drops the model and lets take-aways pass zero; Extra hot uses non-related (coprime) denominators up to 10. Estimate first.",
      tags: ["student quiz", "fractions", "adding fractions", "subtracting fractions", "common denominator", "equivalent fractions", "number line", "estimation", "negatives", "multilingual", "Arabic", "Farsi", "EAL/D"]
    },
    {
      title: "Decimal Zoom Rounding",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/decimal-zoom.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "rounding", "decimals", "number line"]
    },
    {
      title: "Fraction Thinking Explorer",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-thinking-explorer.html",
      note: "Open-ended fraction shuffler for exploration rather than assessment.",
      tags: ["quiz", "fractions", "open ended", "exploration", "reasoning"]
    },
    {
      title: "Fractions Number Line Quiz",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-thinking-quest.html",
      note: "Guided 8-stage progression, trilingual EN/AR/FA, values randomised each attempt.",
      tags: ["quiz", "fractions", "number line", "reasoning", "multilingual", "Arabic", "Farsi", "EAL/D"]
    },
    {
      title: "Fractions, Decimals and Percentages",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fractions-decimals-percentages.html",
      note: "Converting and comparing across all three forms. Saves to the student dashboard.",
      tags: ["quiz", "fractions", "decimals", "percentages", "conversion"]
    },
    {
      title: "Fraction to Percentage",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-to-percentage.html",
      note: "Four levels, 15 questions. Estimate first, then the whole is partitioned, then one part is named and the student counts on. Spicy drops the model entirely.",
      tags: ["student quiz", "fractions", "percentages", "conversion", "number line", "estimation", "recurring"]
    },
    {
      title: "Adding and Subtracting Fractions",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/adding-subtracting-fractions.html",
      note: "Prints the tool's bar + number-line model with each question, or plain cards. Same/related/unrelated/Extra-hot (coprime) ladder or mixed spice, past 1 whole, negatives, answer key. Instructions print bilingually in Arabic or Farsi with English beneath.",
      tags: ["worksheet generator", "printable", "fractions", "adding fractions", "subtracting fractions", "common denominator", "number line", "bar model", "scaffolding", "differentiation", "multilingual", "Arabic", "Farsi", "EAL/D"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-of-amount.html",
      note: "Generates printable questions with answers.",
      tags: ["worksheet generator", "printable", "fraction of an amount"]
    },
    {
      title: "Fractions, Decimals and Percentages",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fractions-decimals-percentages.html",
      note: "Generates printable FDP worksheets with answers.",
      tags: ["worksheet generator", "printable", "fractions", "decimals", "percentages"]
    },
    {
      title: "Fraction to Percentage",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-to-percentage.html",
      note: "Prints the interactive's number line with the fraction marked, or plain conversion questions. Friendly / Terminating / Recurring, past 100%, and an answer key.",
      tags: ["worksheet generator", "printable", "fractions", "percentages", "conversion", "number line", "recurring"]
    },
    {
      title: "Fraction Hex Path",
      kind: "Game",
      url: "/games/fractional-hex.html",
      note: "Simplify a fraction to claim a hex; build an unbroken path across the board.",
      tags: ["game", "simplifying fractions", "equivalence", "strategy", "two player"]
    },
    {
      title: "Math Memory — Fractions & Decimals",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching each fraction to its decimal form.",
      tags: ["game", "memory", "equivalence", "fractions", "decimals", "matching"]
    }
  ],

  "MA4-GEO-C-01": [
    {
      title: "Math Memory — Shapes",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching shapes with their names or properties.",
      tags: ["game", "memory", "2D shapes", "classifying", "triangles", "quadrilaterals"]
    }
  ],

  "MA4-IND-C-01": [
    {
      title: "Factor Circles — Teacher Explore",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/factor-circles/",
      note: "Arrange dots in a circle to reveal factor pairs and groupings.",
      tags: ["factors", "multiples", "primes", "factor pairs", "arrays", "visual"]
    },
    {
      title: "Factor Circles — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/number/factor-circles/lesson-plan.html",
      note: "Full ELPSA sequence for the factor circles tool.",
      tags: ["lesson plan", "ELPSA", "factors", "planning"]
    },
    {
      title: "Products & Factors — Escape the Factor Circle Room",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/factor-circles.html",
      note: "Escape-room styled quiz on products and factors.",
      tags: ["quiz", "factors", "products", "escape room", "gamified"]
    },
    {
      title: "Factors Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/factor-circles.html",
      note: "Generates printable factor worksheets.",
      tags: ["worksheet generator", "printable", "factors", "primes"]
    },
    {
      title: "Dots and Boxes (Multiples mode)",
      kind: "Game",
      url: "/games/dots-and-boxes.html",
      note: "Roll a product, then claim an edge touching a matching multiple. Classic mode also available.",
      tags: ["game", "multiples", "products", "times tables", "strategy", "two player"]
    },
    {
      title: "Math Memory — Powers",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching powers with their values.",
      tags: ["game", "memory", "indices", "powers", "squares", "fluency"]
    }
  ],

  "MA4-INT-C-01": [
    {
      title: "Integer Add/Subtract — Explore",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/integer-addition/",
      note: "Open number-line model for adding and subtracting directed numbers.",
      tags: ["integers", "directed numbers", "number line", "addition", "subtraction"]
    },
    {
      title: "Integer Add/Subtract — Vectors (Combined Signs)",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/integer-combined-signs/",
      note: "Vector arrows on a number line to unpick combined signs such as 5 − (−3).",
      tags: ["integers", "vectors", "combined signs", "number line", "subtracting a negative"]
    },
    {
      title: "Number Line — Missing Value",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/negatives-on-the-number-line/",
      note: "Find the missing value on a number line spanning negatives.",
      tags: ["integers", "number line", "negatives", "missing value"]
    },
    {
      title: "Integer Add/Subtract — Vectors — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/number/integer-combined-signs/lesson-plan.html",
      note: "Full ELPSA sequence for the vectors tool.",
      tags: ["lesson plan", "ELPSA", "integers", "planning"]
    },
    {
      title: "Integer Add/Subtract",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/integer-addition.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "integers", "addition", "subtraction", "number line"]
    },
    {
      title: "Integer Add/Subtract — Combined Signs",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/integer-combined-signs.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "integers", "combined signs", "vectors"]
    },
    {
      title: "Integers — Practice Quiz",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/computation-with-integers.html",
      note: "Four operations with integers. Saves to the student dashboard.",
      tags: ["quiz", "integers", "four operations", "order of operations"]
    },
    {
      title: "Number Line — Missing Value",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/negatives-on-the-number-line.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "integers", "number line", "missing value"]
    },
    {
      title: "Integers — Worksheet Generator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/computation-with-integers/",
      note: "Generates printable integer worksheets with answers.",
      tags: ["worksheet generator", "printable", "integers"]
    },
    {
      title: "Number Line Worksheet Maker",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/negatives-on-the-number-line.html",
      note: "Generates missing-value number-line worksheets.",
      tags: ["worksheet generator", "printable", "number line", "negatives"]
    },
    {
      title: "Number Line Worksheet Maker — Sweet to Extra Hot",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/integer-addition.html",
      note: "Difficulty-scaled number-line worksheets.",
      tags: ["worksheet generator", "printable", "number line", "differentiation"]
    },
    {
      title: "Integer Multiplication",
      kind: "Flip cards",
      url: "/flip-cards/multiply-divide-integers.html",
      note: "Flip-card fluency on multiplying and dividing integers.",
      tags: ["flip cards", "fluency", "integers", "multiplication", "division", "sign rules"]
    }
  ],

  "MA4-LEN-C-01": [
    {
      title: "Perimeter of Plane Shapes",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-plane-shapes/",
      note: "The trace refuses to walk past an unlabelled side. Click a ? and the side it comes from flies across the figure \u2014 an equal side, the pieces of a longer one, or the room left over. 18 shapes over four groups, with a working pad for keeping track of what has been counted.",
      tags: ["perimeter", "plane shapes", "missing side", "composite figures", "L-shape", "T-shape", "U-shape", "staircase", "cross", "regular polygons", "quadrilaterals", "triangles", "equal sides", "trace", "working pad"]
    },
    {
      title: "Perimeter of Plane Shapes",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/perimeter-plane-shapes.html",
      note: "Sweet to Spicy, where the level decides how much of the teaching tool the student keeps \u2014 Sweet hands over the whole thing, Spicy is read-only with half the questions asking for a missing side. Saves to the student dashboard.",
      tags: ["quiz", "perimeter", "plane shapes", "missing side", "composite figures", "differentiation", "sweet mild medium spicy", "student dashboard", "working pad"]
    },
    {
      title: "Perimeter of Plane Shapes",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/perimeter-plane-shapes.html",
      note: "Five sections in the order the sides come before the adding: find a missing side, perimeter with everything labelled, perimeter with sides missing, work backwards from the perimeter, then short contexts. Every figure to scale; the answer key gives the reason, not just the number. Trilingual.",
      tags: ["worksheet generator", "printable", "perimeter", "plane shapes", "missing side", "work backwards", "composite figures", "equal sides", "answer key", "trilingual"]
    },
    {
      title: "Converting Units of Measurement",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/unit-conversion.html",
      note: "Fill a whole number line, then one jump, then bare conversions, comparing and word problems. Stage 3 or Stage 4 unit pairs, four levels. Trilingual, with an answer key.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "length", "mass", "capacity", "worksheet generator", "printable", "trilingual"]
    },
    {
      title: "Unit Conversion \u2014 Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/unit-conversion-number-line/",
      note: "Metric conversions read off a double number line: the 1 : ratio anchor stays on screen and every value is the same scaling of it. Length, mass and capacity, four difficulty tiers, smooth zoom to each new position.",
      tags: ["unit conversion", "metric", "double number line", "length", "mass", "capacity", "proportional reasoning", "scaling", "km", "m", "cm", "mm", "kg", "g", "L", "mL"]
    },
    {
      title: "Area Model Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/",
      note: "Split and rearrange a rectangle to build perimeter and area reasoning.",
      tags: ["perimeter", "area", "rectangles", "area model", "partitioning"]
    },
    {
      title: "Area and Perimeter — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/lesson-plan.html",
      note: "Full ELPSA sequence for the area model tool.",
      tags: ["lesson plan", "ELPSA", "perimeter", "area", "planning"]
    },
    {
      title: "Rectangles — Area / Perimeter",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/perimeter-area-rectangle.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "perimeter", "area", "rectangles"]
    },
    {
      title: "Rectangles — Area / Perimeter",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/perimeter-area-rectangle.html",
      note: "Generates printable perimeter and area worksheets.",
      tags: ["worksheet generator", "printable", "perimeter", "area", "rectangles"]
    },
    {
      title: "Length",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/length/",
      note: "Basic and Expected papers: perimeter of quadrilaterals and composite figures, the parts of a circle, circumference, arc length and sector perimeter. Trilingual, with an answer key.",
      tags: ["worksheet generator", "printable", "perimeter", "circumference", "arc length", "sector", "circle", "quadrilaterals", "composite figures", "pi"]
    }
  ],

  "MA4-LIN-C-01": [
    {
      title: "Capture the Grid",
      kind: "Game",
      url: "/games/cartesian-capture.html",
      note: "Claim coordinate points to capture territory on the Cartesian plane.",
      tags: ["game", "coordinates", "Cartesian plane", "strategy", "two player"]
    },
    {
      title: "Coordinate Battleships",
      kind: "Game",
      url: "/games/battleships.html",
      note: "Place ships on a coordinate grid and attack by typing ordered pairs.",
      tags: ["game", "coordinates", "ordered pairs", "Cartesian plane", "two player"]
    },
    {
      title: "Coordinate Connect 4",
      kind: "Game",
      url: "/games/cartesian-connect-4.html",
      note: "Connect four by naming coordinate pairs.",
      tags: ["game", "coordinates", "Cartesian plane", "two player"]
    }
  ],

  "MA4-PRO-C-01": [
    {
      title: "Probability Spinner Simulator",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Build a spinner, run trials, compare observed with expected frequency.",
      tags: ["probability", "spinner", "simulation", "expected frequency", "experiment"]
    },
    {
      title: "Greedy Pig",
      kind: "Game",
      url: "/games/greedy-pig.html",
      note: "Teacher-led risk and reward dice game — bank before the poison number. Class leaderboard.",
      tags: ["game", "probability", "risk", "expected value", "whole class", "teacher led"]
    },
    {
      title: "Taxed by the King",
      kind: "Game",
      url: "/games/taxed-by-the-king.html",
      note: "Teacher-led card probability game — bank before the King takes his tax. Class leaderboard.",
      tags: ["game", "probability", "risk", "cards", "whole class", "teacher led"]
    }
  ],

  "MA4-PYT-C-01": [
    {
      title: "Pythagoras Theorem — Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/pythagoras-theorem/",
      note: "Generates printable Pythagoras worksheets with diagrams.",
      tags: ["worksheet generator", "printable", "Pythagoras", "right-angled triangles"]
    }
  ],

  "MA4-RAT-C-01": [
    {
      title: "Unit Conversion \u2014 Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/unit-conversion-number-line/",
      note: "The double number line as a proportional tool: one anchor, and every other pair of values is the same multiplier applied to it. Length, mass and capacity.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "ratio", "rates", "length", "mass", "capacity"]
    },
    {
      title: "Converting Units of Measurement",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/unit-conversion.html",
      note: "Proportional reasoning through metric conversion: fill a number line, one jump, fluency, comparing and word problems. Trilingual, with an answer key.",
      tags: ["unit conversion", "metric", "double number line", "proportional reasoning", "scaling", "measurement", "ratio", "rates", "length", "mass", "capacity", "worksheet generator", "printable", "trilingual"]
    },
    {
      title: "Ratio Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/ratios-rates/divide-a-ratio/",
      note: "Divide a quantity in a given ratio, with the parts shown live.",
      tags: ["ratio", "dividing a ratio", "parts", "visual"]
    },
    {
      title: "Stacked Bar Model — Ratio",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/ratios-rates/stacked-bar-ratio/",
      note: "Stacked bar model for comparing ratios and scaling them up.",
      tags: ["ratio", "bar model", "proportion", "scaling", "visual"]
    }
      ,
    {
      title: "Division with a Ratio Table",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/ratio-table-division/",
      note: "The Stage 3 ratio table with an optional Cartesian plane: every row plots as a point, the points fall on a straight line through the origin, and the answer is where that line meets the target.",
      tags: ["ratio table", "proportional reasoning", "rates", "linear relationship", "straight line", "graphing", "Cartesian plane", "origin", "gradient", "stage 3 to stage 4", "division"]
    }
      ,
    {
      title: "Division with a Ratio Table \u2014 Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/ratio-table-division.html",
      note: "A \u201cplot it\u201d section prints the ratio table beside an empty first-quadrant grid with the target drawn on it, so the table and the straight line through the origin are met as the same six numbers.",
      tags: ["worksheet generator", "printable", "ratio table", "proportional reasoning", "rates", "linear relationship", "graphing", "Cartesian plane", "origin", "stage 3 to stage 4", "answer key", "trilingual"]
    }
  ],

  "MA5-ALG-P-01": [
    {
      title: "Complete the Square",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/algebra/complete-the-square/",
      note: "Where (x + p)\u00b2 comes from, as an area: the corner piece that completes the square is b\u00b2/4, seen rather than remembered.",
      tags: ["complete the square", "quadratic", "quadratic equations", "algebra tiles", "area model", "manipulatives", "solving quadratics", "expanding", "factorising", "perfect square", "identity", "stage 5"]
    },
    {
      title: "Complete the Square — Worksheet Creator",
      kind: "Worksheet creator",
      url: "/worksheet-creators/stage-5/algebra/complete-the-square.html",
      note: "Printable A4 practice: label the area model, fill the two blanks, then write expressions in completed square form. Exact answers — halves, quarters and surds, never a rounded decimal.",
      tags: ["complete the square", "completing the square", "quadratic", "quadratic equations", "worksheet", "printable", "area model", "algebra tiles", "completed square form", "solving quadratics", "turning point", "minimum", "surds", "exact answers", "answer key", "differentiated", "stage 5"]
    },
  ],

  "MA5-EQU-P-01": [
    {
      title: "Complete the Square",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/algebra/complete-the-square/",
      note: "Solve a monic quadratic by literally building the square: halve the x-term, put the two halves on two sides, and click the gap to complete it. Handles positive and negative b, and makes the second solution its own step.",
      tags: ["complete the square", "quadratic", "quadratic equations", "algebra tiles", "area model", "manipulatives", "solving quadratics", "monic", "roots", "positive and negative b", "second solution", "stage 5"]
    },
    {
      title: "Complete the Square — Worksheet Creator",
      kind: "Worksheet creator",
      url: "/worksheet-creators/stage-5/algebra/complete-the-square.html",
      note: "Printable A4 practice that walks the same scaffold as the teaching tool: label the model, fill the two blanks, completed square form, then solve equations with room to work. Answer key included.",
      tags: ["complete the square", "completing the square", "quadratic", "quadratic equations", "worksheet", "printable", "area model", "algebra tiles", "completed square form", "solving quadratics", "turning point", "minimum", "surds", "exact answers", "answer key", "differentiated", "stage 5"]
    },
  ],

  "MA5-EQU-P-02": [
    {
      title: "Complete the Square",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/algebra/complete-the-square/",
      note: "The tile build for monic quadratics, plus a Prove the formula mode that runs the same eight moves on ax\u00b2 + bx + c = 0 and lands on the quadratic formula.",
      tags: ["complete the square", "quadratic", "quadratic equations", "algebra tiles", "area model", "manipulatives", "solving quadratics", "quadratic formula", "proof", "derivation", "discriminant", "non-monic", "stage 5"]
    },
    {
      title: "Complete the Square — Worksheet Creator",
      kind: "Worksheet creator",
      url: "/worksheet-creators/stage-5/algebra/complete-the-square.html",
      note: "Printable A4 practice, monic or with a ≠ 1, ending in turning points and “show it is always positive”. Surds stay exact and every answer is generated, not looked up.",
      tags: ["complete the square", "completing the square", "quadratic", "quadratic equations", "worksheet", "printable", "area model", "algebra tiles", "completed square form", "solving quadratics", "turning point", "minimum", "surds", "exact answers", "answer key", "differentiated", "stage 5"]
    },
  ],

  "MA5-FIN-C-01": [
    {
      title: "Financial Expectation Spinner",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Spinner simulation framed around expected financial return over repeated trials.",
      tags: ["probability", "expected value", "financial", "simulation", "spinner"]
    }
  ],

  "MA5-PRO-C-01": [
    {
      title: "Probability Spinner Simulator",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Build a spinner, run many trials, and compare observed relative frequency with theoretical probability.",
      tags: ["probability", "spinner", "simulation", "relative frequency", "expected value", "experiment"]
    }
  ]
};
