/* ============================================================================
   Mills Maths Tools — Resources by Stage : TOOL LINKS  (auto-derived)
   ----------------------------------------------------------------------------
   Interactive tools, student quizzes, worksheet makers, flip cards, games and
   ELPSA lesson plans, mapped to the NSW syllabus outcome each one serves.

   WHY THIS IS A SEPARATE FILE
   ---------------------------
   `resourcesManifest.js` holds the outcomes and YOUR uploaded PDFs — that is
   the file you hand-edit. This file is the wiring for pages that already exist
   elsewhere on the site, so it can be regenerated by walking the repo without
   touching anything you have typed.

   SHAPE
   -----
     "MA4-ALG-C-01": [ { title, kind, url, note, tags[] }, ... ]

   `kind` renders as the small right-hand label and drives sort order within an
   outcome: Teacher tool -> Lesson plan -> Student quiz -> Worksheet maker ->
   Flip cards -> Game.

   NOTES
   -----
   * A tool may appear under several outcomes on purpose (cross-listing). The
     Protractor tool serves both MA3-GM-03 and MA4-ANG-C-01; nothing is
     duplicated on disk, both rows point at the same URL.
   * All URLs are site-absolute so they work from any page depth.
   * The Revision Generator (Exam Builder) is deliberately NOT listed here.
   ========================================================================== */

window.MMT_TOOL_LINKS = {
  "MA3-2DS-01": [
    {
      title: "Math Memory — Shapes",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching shapes with their names or properties.",
      tags: ["game", "memory", "2D shapes", "classifying", "matching"]
    }
  ],

  "MA3-2DS-02": [
    {
      title: "Area Model Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/",
      note: "Split and rearrange a rectangle to build area and perimeter reasoning.",
      tags: ["area", "perimeter", "rectangles", "area model", "partitioning"]
    },
    {
      title: "Rectangles — Area / Perimeter",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/perimeter-area-rectangle.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "area", "perimeter", "rectangles"]
    },
    {
      title: "Shikaku",
      kind: "Game",
      url: "/games/shikaku.html",
      note: "Divide the grid into rectangles whose areas match the clue numbers.",
      tags: ["game", "puzzle", "area", "rectangles", "factors", "logic"]
    }
  ],

  "MA3-2DS-03": [
    {
      title: "Area of a Triangle — Half the Rectangle",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/area-of-a-triangle/",
      note: "Shows a triangle as half its enclosing rectangle, draggable.",
      tags: ["area", "triangles", "rectangles", "derivation", "visual"]
    }
  ],

  "MA3-AR-01": [
    {
      title: "Partition Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/partition-splitter/",
      note: "Split a number into parts on a place-value display to model addition strategies.",
      tags: ["partitioning", "place value", "addition", "mental strategies"]
    },
    {
      title: "Rows & Columns Challenge",
      kind: "Game",
      url: "/games/row-column-challenge.html",
      note: "Two-player strategy game: take a number from the active row or column and add it to your total. After Dr Paul Swan.",
      tags: ["game", "strategy", "addition", "mental computation", "two player"]
    },
    {
      title: "Partition Splitter — Class Flash Cards",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/partition-splitter/partition-flash.html",
      note: "Projected partitioning flash round for the whole class.",
      tags: ["flash cards", "partitioning", "whole class"]
    },
    {
      title: "Partition Splitter — Student Practice",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/partition-splitter/student-flash.html",
      note: "Self-paced student partitioning practice.",
      tags: ["flash cards", "partitioning", "independent practice"]
    }
  ],

  "MA3-CHAN-01": [
    {
      title: "Probability Spinner Simulator",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Build a spinner, run trials, compare observed with expected frequency.",
      tags: ["probability", "spinner", "simulation", "expected value", "experiment"]
    },
    {
      title: "Greedy Pig",
      kind: "Game",
      url: "/games/greedy-pig.html",
      note: "Teacher-led risk and reward dice game — bank before the poison number. Class leaderboard.",
      tags: ["game", "probability", "risk", "expected value", "whole class", "teacher led"]
    },
    {
      title: "Taxed by the King",
      kind: "Game",
      url: "/games/taxed-by-the-king.html",
      note: "Teacher-led card probability game — bank before the King takes his tax. Class leaderboard.",
      tags: ["game", "probability", "risk", "cards", "whole class", "teacher led"]
    }
  ],

  "MA3-GM-01": [
    {
      title: "Capture the Grid",
      kind: "Game",
      url: "/games/cartesian-capture.html",
      note: "Claim coordinate points to capture territory on the Cartesian plane.",
      tags: ["game", "coordinates", "Cartesian plane", "strategy", "two player"]
    },
    {
      title: "Coordinate Battleships",
      kind: "Game",
      url: "/games/battleships.html",
      note: "Place ships on a coordinate grid and attack by typing ordered pairs.",
      tags: ["game", "coordinates", "ordered pairs", "Cartesian plane", "two player"]
    },
    {
      title: "Coordinate Connect 4",
      kind: "Game",
      url: "/games/cartesian-connect-4.html",
      note: "Connect four by naming coordinate pairs.",
      tags: ["game", "coordinates", "Cartesian plane", "two player"]
    }
  ],

  "MA3-GM-03": [
    {
      title: "Protractor Angle Explorer",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/reading-a-protractor/",
      note: "Drag a protractor onto an angle and read the scale, inner and outer.",
      tags: ["protractor", "measuring angles", "angle types"]
    },
    {
      title: "Reading a Protractor",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/reading-a-protractor.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "protractor", "measuring angles"]
    },
    {
      title: "Angle Types Flip Fluency",
      kind: "Flip cards",
      url: "/flip-cards/Geometry/angles.html",
      note: "Flip-card fluency on acute, obtuse, reflex and right angles.",
      tags: ["flip cards", "angle types", "fluency", "classifying"]
    }
  ],

  "MA3-MR-01": [
    {
      title: "Factor Circles — Teacher Explore",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/factor-circles/",
      note: "Arrange dots in a circle to reveal factor pairs and groupings.",
      tags: ["factors", "multiples", "factor pairs", "arrays", "visual"]
    },
    {
      title: "Times Table Chart — Area, Product, Division, Fractions",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/timestable-chart/",
      note: "One chart, four lenses: array area, product, division and fraction of an amount.",
      tags: ["times tables", "arrays", "multiplication", "division", "factors", "visual"]
    },
    {
      title: "Products & Factors — Escape the Factor Circle Room",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/factor-circles.html",
      note: "Escape-room styled quiz on products and factors. Saves to the student dashboard.",
      tags: ["quiz", "factors", "products", "escape room", "gamified"]
    },
    {
      title: "Factoring for Multiplication",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/multiplicative-strategies/",
      note: "Generates worksheets on factorising to make multiplication easier.",
      tags: ["worksheet generator", "printable", "factors", "multiplicative strategies"]
    },
    {
      title: "Factors Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/factor-circles.html",
      note: "Generates printable factor worksheets.",
      tags: ["worksheet generator", "printable", "factors"]
    },
    {
      title: "Closest to 100",
      kind: "Game",
      url: "/games/closest-to-100.html",
      note: "Roll two dice, state the product, then draw the matching array on a hundred grid. Closest to 100 wins.",
      tags: ["game", "dice", "arrays", "multiplication", "area", "two player"]
    },
    {
      title: "Dots and Boxes (Multiples mode)",
      kind: "Game",
      url: "/games/dots-and-boxes.html",
      note: "Roll a product, then claim an edge touching a matching multiple. Classic mode also available.",
      tags: ["game", "multiples", "products", "times tables", "strategy", "two player"]
    },
    {
      title: "Math Memory — Multiplication",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching multiplication facts.",
      tags: ["game", "memory", "multiplication", "fluency", "matching"]
    }
  ],

  "MA3-NSM-02": [
    {
      title: "Math Memory — Clocks",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching analogue clocks to digital times.",
      tags: ["game", "memory", "time", "analogue", "digital", "matching"]
    }
  ],

  "MA3-RN-01": [
    {
      title: "Place Value: Multiply & Divide by 10",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-3/number/multiply-divide-by-ten/",
      note: "Drag digits through a place-value grid to see ×10 and ÷10 shift the whole number.",
      tags: ["place value", "powers of 10", "decimals", "multiply", "divide"]
    },
    {
      title: "Whole Number Zoom Rounding",
      kind: "Student quiz",
      url: "/online-quizzes/stage-3/number/whole-number-zoom.html",
      note: "Zoomable number line for rounding whole numbers. Saves to the student dashboard.",
      tags: ["rounding", "number line", "place value", "quiz"]
    },
    {
      title: "Multiply & Divide by Powers of 10",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-3/number/multiply-divide-by-ten.html",
      note: "Generates a printable worksheet with answers.",
      tags: ["worksheet generator", "printable", "powers of 10"]
    },
    {
      title: "Divide by 10",
      kind: "Flip cards",
      url: "/flip-cards/divide-by-tens.html",
      note: "Quick flip-card fluency on dividing by 10.",
      tags: ["flip cards", "fluency", "division", "place value"]
    },
    {
      title: "Multiply & Divide by 10 — Class Flash Cards",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/multiply-divide-by-ten/flash-cards.html",
      note: "Whole-class projected flash card round.",
      tags: ["flash cards", "fluency", "place value", "whole class"]
    },
    {
      title: "Multiply & Divide by 10 — Student Practice",
      kind: "Flash cards",
      url: "/interactive-tools/stage-3/number/multiply-divide-by-ten/student-flash.html",
      note: "Self-paced student version of the flash cards.",
      tags: ["flash cards", "fluency", "independent practice"]
    }
  ],

  "MA3-RN-03": [
    {
      title: "Math Memory — Fractions & Decimals",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching each fraction to its decimal form. Pass-and-play or online.",
      tags: ["game", "memory", "equivalence", "fractions", "decimals", "matching"]
    }
  ],

  "MA3-RQF-01": [
    {
      title: "Fraction Hex Path",
      kind: "Game",
      url: "/games/fractional-hex.html",
      note: "Simplify a fraction to claim a hex; build an unbroken path across the board.",
      tags: ["game", "simplifying fractions", "equivalence", "strategy", "two player"]
    }
  ],

  "MA3-RQF-02": [
    {
      title: "Times Table Chart — Fractions of an Amount",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-of-amount/",
      note: "Uses the times-table grid to find a fraction of an amount.",
      tags: ["fraction of an amount", "times tables", "visual", "arrays"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-of-amount.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "fraction of an amount"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-of-amount.html",
      note: "Generates printable questions with answers.",
      tags: ["worksheet generator", "printable", "fraction of an amount"]
    }
  ],

  "MA4-ALG-C-01": [
    {
      title: "Collecting Like Terms",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/collecting-like-terms/",
      note: "Group and combine like terms with visual term tiles.",
      tags: ["algebra", "like terms", "simplifying", "coefficients", "visual"]
    },
    {
      title: "Number Pattern (Coefficient Groups)",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/number-groups/",
      note: "Set how many terms and the total of the coefficients, then reveal and combine.",
      tags: ["algebra", "like terms", "coefficients", "generalising", "patterns"]
    },
    {
      title: "Substitution in Algebra",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/substitution/",
      note: "Substitute values into expressions and watch each step evaluate.",
      tags: ["algebra", "substitution", "evaluating", "expressions"]
    },
    {
      title: "Collecting Like Terms — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/collecting-like-terms/lesson-plan.html",
      note: "Full ELPSA sequence for the like-terms tool.",
      tags: ["lesson plan", "ELPSA", "algebra", "planning"]
    },
    {
      title: "Number Pattern — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/number-groups/lesson-plan.html",
      note: "Full ELPSA sequence for the coefficient-groups tool.",
      tags: ["lesson plan", "ELPSA", "algebra", "planning"]
    },
    {
      title: "Substitution in Algebra — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/substitution/lesson-plan.html",
      note: "Full ELPSA sequence for the substitution tool.",
      tags: ["lesson plan", "ELPSA", "algebra", "planning"]
    },
    {
      title: "Algebraic Techniques",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/algebraic-techniques.html",
      note: "Covers simplifying, expanding and factorising. Sub-topic quiz links can be built from this page.",
      tags: ["quiz", "algebra", "simplifying", "expanding", "factorising", "subset builder"]
    },
    {
      title: "Collecting Like Terms",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/collecting-like-terms.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "algebra", "like terms", "simplifying"]
    },
    {
      title: "Number Groups",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/number-groups.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "algebra", "like terms", "coefficients"]
    },
    {
      title: "Substitution in Algebra",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/substitution.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "algebra", "substitution", "evaluating"]
    },
    {
      title: "Algebraic Techniques",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/algebraic-techniques/",
      note: "Generates printable algebra worksheets with answers.",
      tags: ["worksheet generator", "printable", "algebra", "simplifying", "expanding"]
    },
    {
      title: "Collecting Like Terms",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/collecting-like-terms.html",
      note: "Generates printable like-terms worksheets.",
      tags: ["worksheet generator", "printable", "like terms"]
    },
    {
      title: "Collecting Like Terms (Number Groups)",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/number-groups.html",
      note: "Coefficient-group variant of the like-terms worksheet creator.",
      tags: ["worksheet generator", "printable", "like terms", "coefficients"]
    },
    {
      title: "Substitution in Algebra",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/substitution.html",
      note: "Generates printable substitution worksheets.",
      tags: ["worksheet generator", "printable", "substitution"]
    },
    {
      title: "Translate Words to Algebra",
      kind: "Flip cards",
      url: "/flip-cards/algebra-to-words.html",
      note: "Flip-card fluency converting worded phrases into algebraic expressions.",
      tags: ["flip cards", "fluency", "algebra", "worded problems", "translating"]
    }
  ],

  "MA4-ANG-C-01": [
    {
      title: "Angle Relationships on Parallel Lines",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/angles-parallel-lines/",
      note: "Drag a transversal across parallel lines and watch co-interior, alternate and corresponding angles update.",
      tags: ["angles", "parallel lines", "transversal", "corresponding", "alternate", "co-interior"]
    },
    {
      title: "Protractor Angle Explorer",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/reading-a-protractor/",
      note: "Drag a protractor onto an angle and read the scale, inner and outer.",
      tags: ["protractor", "measuring angles", "angle types"]
    },
    {
      title: "Angle Relationships",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/angle-relationships.html",
      note: "Sub-topic quiz links can be built from this page.",
      tags: ["quiz", "angles", "parallel lines", "transversal", "subset builder"]
    },
    {
      title: "Reading a Protractor",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/reading-a-protractor.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "protractor", "measuring angles"]
    },
    {
      title: "Angle Relationships",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/angle-relationships/",
      note: "Generates printable angle-relationship worksheets with diagrams.",
      tags: ["worksheet generator", "printable", "angles", "parallel lines"]
    },
    {
      title: "Angle Relationships",
      kind: "Flip cards",
      url: "/flip-cards/Angles-parallel-lines/",
      note: "Flip-card fluency on angle relationships formed by parallel lines.",
      tags: ["flip cards", "fluency", "angles", "parallel lines", "transversal"]
    },
    {
      title: "Angle Types Flip Fluency",
      kind: "Flip cards",
      url: "/flip-cards/Geometry/angles.html",
      note: "Flip-card fluency on acute, obtuse, reflex and right angles.",
      tags: ["flip cards", "fluency", "angle types", "classifying"]
    }
  ],

  "MA4-ARE-C-01": [
    {
      title: "Area Model Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/",
      note: "Split and rearrange a rectangle to build area reasoning and composite area.",
      tags: ["area", "rectangles", "area model", "composite area", "partitioning"]
    },
    {
      title: "Area of a Triangle — Half the Rectangle",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/area-of-a-triangle/",
      note: "Shows a triangle as half its enclosing rectangle, draggable.",
      tags: ["area", "triangles", "rectangles", "derivation", "visual"]
    },
    {
      title: "Area Model",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/area-model.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "area", "area model", "composite area"]
    },
    {
      title: "Area of a Triangle",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/area-of-a-triangle.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "area", "triangles"]
    },
    {
      title: "Triangles — Area Worksheet Maker",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/area-of-a-triangle.html",
      note: "Generates printable triangle-area worksheets.",
      tags: ["worksheet generator", "printable", "area", "triangles"]
    },
    {
      title: "Shikaku",
      kind: "Game",
      url: "/games/shikaku.html",
      note: "Divide the grid into rectangles whose areas match the clue numbers.",
      tags: ["game", "puzzle", "area", "rectangles", "factors", "logic"]
    }
  ],

  "MA4-EQU-C-01": [
    {
      title: "Equations — Double Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/algebra/double-numberline/",
      note: "Solve one- and two-step equations on a double number line, keeping both sides balanced.",
      tags: ["equations", "double number line", "solving", "inverse operations", "balance"]
    },
    {
      title: "Double Number Line Equations — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/algebra/double-numberline/lesson-plan.html",
      note: "Full ELPSA sequence for the double number line tool.",
      tags: ["lesson plan", "ELPSA", "equations", "planning"]
    },
    {
      title: "Addition & Subtraction Equations",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/double-numberline/student-quiz-add-subtract.html",
      note: "One-step equations, additive. Saves to the student dashboard.",
      tags: ["quiz", "equations", "one step", "addition", "subtraction"]
    },
    {
      title: "Equations",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/equations.html",
      note: "Sub-topic quiz links can be built from this page.",
      tags: ["quiz", "equations", "solving", "subset builder"]
    },
    {
      title: "Equations — Double Number Line",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/double-numberline/student-quiz.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "equations", "double number line"]
    },
    {
      title: "Multiplication & Division Equations",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/algebra/double-numberline/student-quiz-mult-div.html",
      note: "One-step equations, multiplicative. Saves to the student dashboard.",
      tags: ["quiz", "equations", "one step", "multiplication", "division"]
    },
    {
      title: "Equations",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/equations/",
      note: "Generates printable equation worksheets with answers.",
      tags: ["worksheet generator", "printable", "equations"]
    },
    {
      title: "One Step Equations",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/algebra/double-numberline.html",
      note: "Generates printable one-step equation worksheets.",
      tags: ["worksheet generator", "printable", "equations", "one step"]
    }
  ],

  "MA4-FRC-C-01": [
    {
      title: "Decimal Zoom Rounding",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/rounding-decimals/",
      note: "Zoom into a number line to see which decimal place a value rounds to.",
      tags: ["rounding", "decimals", "number line", "zoom", "place value"]
    },
    {
      title: "Fraction Grid to Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-grid-number-line/",
      note: "The hundred flat (or any area grid) is shaded, then its parts lift off and rearrange into the whole journey from 0 to 1 \u2014 so a part-whole count becomes ONE point on a number line. Estimate-first, benchmark ghosts, regroup-and-rename, decimal, percentage and a second fraction to compare.",
      tags: ["fractions", "decimals", "percentages", "number line", "area model", "hundred grid", "MAB", "part-whole", "equivalent fractions", "estimation", "density", "comparing fractions", "recurring"]
    },
    {
      title: "Fraction Grid to Number Line",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-grid-number-line.html",
      note: "Every card carries the area grid AND a number line, so the fraction has to travel between them. Four question kinds \u2014 shade then place the point, place then shade, name it four ways, and compare two \u2014 plus a full-width misconception prompt on each page. The ladder raises the demand on the LINE: matching parts, then tenths, then a different unit, then only 0, \u00bd and 1.",
      tags: ["worksheet", "fractions", "decimals", "percentages", "number line", "area model", "hundred grid", "equivalent fractions", "simplest form", "comparing fractions", "reasoning", "misconceptions"]
    },
    {
      title: "Fraction Bar + Number Line",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-bar-number-line/",
      note: "One fraction shown three ways: part-whole bar, point on a double number line, and as division. Denominators 2-100.",
      tags: ["fractions", "decimals", "number line", "fraction bar", "division", "equivalence", "recurring"]
    },
    {
      title: "Fraction to Percentage",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-to-percentage/",
      note: "Fraction above the line, percentage below. Step-by-step reveals find one part of 100, then count on. Estimate-first predict mode; handles recurring percentages and past 100%.",
      tags: ["fractions", "percentages", "conversion", "number line", "estimation", "recurring", "per cent", "unit fraction"]
    },
    {
      title: "Adding and Subtracting Fractions",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/adding-fractions/",
      note: "Two fraction bars join on a number line, are renamed with a common denominator (equivalents shown under the bar), and the pieces are counted. Predict mode, a misconception step, and subtraction that can pass zero.",
      tags: ["fractions", "adding fractions", "subtracting fractions", "common denominator", "equivalent fractions", "number line", "bar model", "renaming", "negatives"]
    },
    {
      title: "Times Table Chart — Fractions of an Amount",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/fraction-of-amount/",
      note: "Uses the times-table grid to find a fraction of an amount.",
      tags: ["fraction of an amount", "times tables", "visual", "arrays"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-of-amount.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "fraction of an amount"]
    },
    {
      title: "Adding and Subtracting Fractions",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/adding-subtracting-fractions.html",
      note: "Five levels, 15 questions, trilingual EN/AR/FA, with an equation-editor answer box (fraction button). Sweet counts like parts; Mild renames one bar; Medium renames both (all three have back/forward reveal arrows); Spicy drops the model and lets take-aways pass zero; Extra hot uses non-related (coprime) denominators up to 10. Estimate first.",
      tags: ["student quiz", "fractions", "adding fractions", "subtracting fractions", "common denominator", "equivalent fractions", "number line", "estimation", "negatives", "multilingual", "Arabic", "Farsi", "EAL/D"]
    },
    {
      title: "Decimal Zoom Rounding",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/decimal-zoom.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "rounding", "decimals", "number line"]
    },
    {
      title: "Fraction Thinking Explorer",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-thinking-explorer.html",
      note: "Open-ended fraction shuffler for exploration rather than assessment.",
      tags: ["quiz", "fractions", "open ended", "exploration", "reasoning"]
    },
    {
      title: "Fractions Number Line Quiz",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-thinking-quest.html",
      note: "Guided 8-stage progression, trilingual EN/AR/FA, values randomised each attempt.",
      tags: ["quiz", "fractions", "number line", "reasoning", "multilingual", "Arabic", "Farsi", "EAL/D"]
    },
    {
      title: "Fractions, Decimals and Percentages",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fractions-decimals-percentages.html",
      note: "Converting and comparing across all three forms. Saves to the student dashboard.",
      tags: ["quiz", "fractions", "decimals", "percentages", "conversion"]
    },
    {
      title: "Fraction to Percentage",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/fraction-to-percentage.html",
      note: "Four levels, 15 questions. Estimate first, then the whole is partitioned, then one part is named and the student counts on. Spicy drops the model entirely.",
      tags: ["student quiz", "fractions", "percentages", "conversion", "number line", "estimation", "recurring"]
    },
    {
      title: "Adding and Subtracting Fractions",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/adding-subtracting-fractions.html",
      note: "Prints the tool's bar + number-line model with each question, or plain cards. Same/related/unrelated/Extra-hot (coprime) ladder or mixed spice, past 1 whole, negatives, answer key. Instructions print bilingually in Arabic or Farsi with English beneath.",
      tags: ["worksheet generator", "printable", "fractions", "adding fractions", "subtracting fractions", "common denominator", "number line", "bar model", "scaffolding", "differentiation", "multilingual", "Arabic", "Farsi", "EAL/D"]
    },
    {
      title: "Calculating Fractions of Amounts",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-of-amount.html",
      note: "Generates printable questions with answers.",
      tags: ["worksheet generator", "printable", "fraction of an amount"]
    },
    {
      title: "Fractions, Decimals and Percentages",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fractions-decimals-percentages.html",
      note: "Generates printable FDP worksheets with answers.",
      tags: ["worksheet generator", "printable", "fractions", "decimals", "percentages"]
    },
    {
      title: "Fraction to Percentage",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/fraction-to-percentage.html",
      note: "Prints the interactive's number line with the fraction marked, or plain conversion questions. Friendly / Terminating / Recurring, past 100%, and an answer key.",
      tags: ["worksheet generator", "printable", "fractions", "percentages", "conversion", "number line", "recurring"]
    },
    {
      title: "Fraction Hex Path",
      kind: "Game",
      url: "/games/fractional-hex.html",
      note: "Simplify a fraction to claim a hex; build an unbroken path across the board.",
      tags: ["game", "simplifying fractions", "equivalence", "strategy", "two player"]
    },
    {
      title: "Math Memory — Fractions & Decimals",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching each fraction to its decimal form.",
      tags: ["game", "memory", "equivalence", "fractions", "decimals", "matching"]
    }
  ],

  "MA4-GEO-C-01": [
    {
      title: "Math Memory — Shapes",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching shapes with their names or properties.",
      tags: ["game", "memory", "2D shapes", "classifying", "triangles", "quadrilaterals"]
    }
  ],

  "MA4-IND-C-01": [
    {
      title: "Factor Circles — Teacher Explore",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/factor-circles/",
      note: "Arrange dots in a circle to reveal factor pairs and groupings.",
      tags: ["factors", "multiples", "primes", "factor pairs", "arrays", "visual"]
    },
    {
      title: "Factor Circles — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/number/factor-circles/lesson-plan.html",
      note: "Full ELPSA sequence for the factor circles tool.",
      tags: ["lesson plan", "ELPSA", "factors", "planning"]
    },
    {
      title: "Products & Factors — Escape the Factor Circle Room",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/factor-circles.html",
      note: "Escape-room styled quiz on products and factors.",
      tags: ["quiz", "factors", "products", "escape room", "gamified"]
    },
    {
      title: "Factors Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/factor-circles.html",
      note: "Generates printable factor worksheets.",
      tags: ["worksheet generator", "printable", "factors", "primes"]
    },
    {
      title: "Dots and Boxes (Multiples mode)",
      kind: "Game",
      url: "/games/dots-and-boxes.html",
      note: "Roll a product, then claim an edge touching a matching multiple. Classic mode also available.",
      tags: ["game", "multiples", "products", "times tables", "strategy", "two player"]
    },
    {
      title: "Math Memory — Powers",
      kind: "Game",
      url: "/games/Maths%20Memory/",
      note: "Memory game matching powers with their values.",
      tags: ["game", "memory", "indices", "powers", "squares", "fluency"]
    }
  ],

  "MA4-INT-C-01": [
    {
      title: "Integer Add/Subtract — Explore",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/integer-addition/",
      note: "Open number-line model for adding and subtracting directed numbers.",
      tags: ["integers", "directed numbers", "number line", "addition", "subtraction"]
    },
    {
      title: "Integer Add/Subtract — Vectors (Combined Signs)",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/integer-combined-signs/",
      note: "Vector arrows on a number line to unpick combined signs such as 5 − (−3).",
      tags: ["integers", "vectors", "combined signs", "number line", "subtracting a negative"]
    },
    {
      title: "Number Line — Missing Value",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/number/negatives-on-the-number-line/",
      note: "Find the missing value on a number line spanning negatives.",
      tags: ["integers", "number line", "negatives", "missing value"]
    },
    {
      title: "Integer Add/Subtract — Vectors — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/number/integer-combined-signs/lesson-plan.html",
      note: "Full ELPSA sequence for the vectors tool.",
      tags: ["lesson plan", "ELPSA", "integers", "planning"]
    },
    {
      title: "Integer Add/Subtract",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/integer-addition.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "integers", "addition", "subtraction", "number line"]
    },
    {
      title: "Integer Add/Subtract — Combined Signs",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/integer-combined-signs.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "integers", "combined signs", "vectors"]
    },
    {
      title: "Integers — Practice Quiz",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/computation-with-integers.html",
      note: "Four operations with integers. Saves to the student dashboard.",
      tags: ["quiz", "integers", "four operations", "order of operations"]
    },
    {
      title: "Number Line — Missing Value",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/number/negatives-on-the-number-line.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "integers", "number line", "missing value"]
    },
    {
      title: "Integers — Worksheet Generator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/computation-with-integers/",
      note: "Generates printable integer worksheets with answers.",
      tags: ["worksheet generator", "printable", "integers"]
    },
    {
      title: "Number Line Worksheet Maker",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/negatives-on-the-number-line.html",
      note: "Generates missing-value number-line worksheets.",
      tags: ["worksheet generator", "printable", "number line", "negatives"]
    },
    {
      title: "Number Line Worksheet Maker — Sweet to Extra Hot",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/number/integer-addition.html",
      note: "Difficulty-scaled number-line worksheets.",
      tags: ["worksheet generator", "printable", "number line", "differentiation"]
    },
    {
      title: "Integer Multiplication",
      kind: "Flip cards",
      url: "/flip-cards/multiply-divide-integers.html",
      note: "Flip-card fluency on multiplying and dividing integers.",
      tags: ["flip cards", "fluency", "integers", "multiplication", "division", "sign rules"]
    }
  ],

  "MA4-LEN-C-01": [
    {
      title: "Area Model Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/",
      note: "Split and rearrange a rectangle to build perimeter and area reasoning.",
      tags: ["perimeter", "area", "rectangles", "area model", "partitioning"]
    },
    {
      title: "Area and Perimeter — ELPSA Lesson Plan",
      kind: "Lesson plan",
      url: "/interactive-tools/stage-4/measurement-space/perimeter-area-rectangle/lesson-plan.html",
      note: "Full ELPSA sequence for the area model tool.",
      tags: ["lesson plan", "ELPSA", "perimeter", "area", "planning"]
    },
    {
      title: "Rectangles — Area / Perimeter",
      kind: "Student quiz",
      url: "/online-quizzes/stage-4/measurement-space/perimeter-area-rectangle.html",
      note: "Saves to the student dashboard.",
      tags: ["quiz", "perimeter", "area", "rectangles"]
    },
    {
      title: "Rectangles — Area / Perimeter",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/perimeter-area-rectangle.html",
      note: "Generates printable perimeter and area worksheets.",
      tags: ["worksheet generator", "printable", "perimeter", "area", "rectangles"]
    }
  ],

  "MA4-LIN-C-01": [
    {
      title: "Capture the Grid",
      kind: "Game",
      url: "/games/cartesian-capture.html",
      note: "Claim coordinate points to capture territory on the Cartesian plane.",
      tags: ["game", "coordinates", "Cartesian plane", "strategy", "two player"]
    },
    {
      title: "Coordinate Battleships",
      kind: "Game",
      url: "/games/battleships.html",
      note: "Place ships on a coordinate grid and attack by typing ordered pairs.",
      tags: ["game", "coordinates", "ordered pairs", "Cartesian plane", "two player"]
    },
    {
      title: "Coordinate Connect 4",
      kind: "Game",
      url: "/games/cartesian-connect-4.html",
      note: "Connect four by naming coordinate pairs.",
      tags: ["game", "coordinates", "Cartesian plane", "two player"]
    }
  ],

  "MA4-PRO-C-01": [
    {
      title: "Probability Spinner Simulator",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Build a spinner, run trials, compare observed with expected frequency.",
      tags: ["probability", "spinner", "simulation", "expected frequency", "experiment"]
    },
    {
      title: "Greedy Pig",
      kind: "Game",
      url: "/games/greedy-pig.html",
      note: "Teacher-led risk and reward dice game — bank before the poison number. Class leaderboard.",
      tags: ["game", "probability", "risk", "expected value", "whole class", "teacher led"]
    },
    {
      title: "Taxed by the King",
      kind: "Game",
      url: "/games/taxed-by-the-king.html",
      note: "Teacher-led card probability game — bank before the King takes his tax. Class leaderboard.",
      tags: ["game", "probability", "risk", "cards", "whole class", "teacher led"]
    }
  ],

  "MA4-PYT-C-01": [
    {
      title: "Pythagoras Theorem — Worksheet Creator",
      kind: "Worksheet maker",
      url: "/worksheet-creators/stage-4/measurement-space/pythagoras-theorem/",
      note: "Generates printable Pythagoras worksheets with diagrams.",
      tags: ["worksheet generator", "printable", "Pythagoras", "right-angled triangles"]
    }
  ],

  "MA4-RAT-C-01": [
    {
      title: "Ratio Splitter",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/ratios-rates/divide-a-ratio/",
      note: "Divide a quantity in a given ratio, with the parts shown live.",
      tags: ["ratio", "dividing a ratio", "parts", "visual"]
    },
    {
      title: "Stacked Bar Model — Ratio",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-4/ratios-rates/stacked-bar-ratio/",
      note: "Stacked bar model for comparing ratios and scaling them up.",
      tags: ["ratio", "bar model", "proportion", "scaling", "visual"]
    }
  ],

  "MA5-FIN-C-01": [
    {
      title: "Financial Expectation Spinner",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Spinner simulation framed around expected financial return over repeated trials.",
      tags: ["probability", "expected value", "financial", "simulation", "spinner"]
    }
  ],

  "MA5-PRO-C-01": [
    {
      title: "Probability Spinner Simulator",
      kind: "Teacher tool",
      url: "/interactive-tools/stage-5/statistics-probability/financial-expectation-spinner/",
      note: "Build a spinner, run many trials, and compare observed relative frequency with theoretical probability.",
      tags: ["probability", "spinner", "simulation", "relative frequency", "expected value", "experiment"]
    }
  ]
};
